using System.Text;
using System.Text.Json;
using Shieldsmith.Core.Export;
using Shieldsmith.Core.Models;
using Shieldsmith.Outputs.Markdown;

namespace Shieldsmith.ExportPack;

/// <summary>
/// Writes a solution "docpack": a folder a user opens in their own Claude Code
/// terminal to ask questions about the solution. It carries the canonical JSON,
/// the full Markdown documentation, a CLAUDE.md with grounding rules, and a
/// question-answering skill. No API key and no Shieldsmith AI involvement: the
/// user's own Claude Code does the reading.
/// </summary>
public static class ExportPackWriter
{
    public static string Write(SolutionModel model, string outputDirectory,
        string? erdPngPath = null, GeneratedInterpretation? interpretation = null)
    {
        var packDir = Path.Combine(outputDirectory, $"{model.UniqueName}_docpack");
        Directory.CreateDirectory(packDir);

        // The canonical JSON and the Markdown tree are the same extractions the
        // other outputs use; the pack is assembly, not re-derivation.
        File.WriteAllText(Path.Combine(packDir, "solution.json"),
            SolutionJsonExporter.ToJson(model, redactEnvironmentValues: false));
        MarkdownReportBuilder.Write(model, Path.Combine(packDir, "docs"), erdPngPath, interpretation);

        File.WriteAllText(Path.Combine(packDir, "manifest.json"), BuildManifest(model));
        File.WriteAllText(Path.Combine(packDir, "CLAUDE.md"), BuildClaudeMd(model));

        var skillDir = Path.Combine(packDir, ".claude", "skills", "solution-qa");
        Directory.CreateDirectory(skillDir);
        File.WriteAllText(Path.Combine(skillDir, "SKILL.md"), BuildSkill(model));

        return packDir;
    }

    private static string BuildManifest(SolutionModel model)
    {
        var manifest = new
        {
            generator = "Shieldsmith",
            solution = new { model.UniqueName, model.DisplayName, model.Version, model.IsManaged },
            publisher = model.PublisherDisplayName,
            counts = new
            {
                components = model.RootComponents.Count,
                tables = model.Entities.Count,
                oneToManyRelationships = model.OneToManyRelationships.Count,
                manyToManyRelationships = model.ManyToManyRelationships.Count,
                processes = model.Processes.Count,
                environmentVariables = model.EnvironmentVariables.Count,
            },
            files = new
            {
                canonicalJson = "solution.json",
                documentation = "docs/index.md",
                tables = "docs/tables/",
                flows = "docs/flows/",
            },
        };
        return JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });
    }

    private static string BuildClaudeMd(SolutionModel model)
    {
        var md = new StringBuilder();
        md.AppendLine($"# {model.DisplayName}: solution documentation pack");
        md.AppendLine();
        md.AppendLine("This folder was generated by Shieldsmith from a Power Platform solution export. It exists so");
        md.AppendLine("you can answer questions about the solution accurately, from the extracted files alone.");
        md.AppendLine();
        md.AppendLine("## Grounding rules");
        md.AppendLine();
        md.AppendLine("- Answer only from the files in this pack. `solution.json` is the complete canonical");
        md.AppendLine("  extraction; `docs/` is the same content as readable Markdown.");
        md.AppendLine("- Cite the file (and table or flow name) each answer comes from.");
        md.AppendLine("- If something is not in the pack, say so. Do not fill gaps with what similar solutions");
        md.AppendLine("  usually do. Solution exports do not contain business records, audit history, run");
        md.AppendLine("  history, or environment configuration beyond what is in these files.");
        md.AppendLine("- Blocks marked \"Generated interpretation\" in the docs are AI commentary produced at");
        md.AppendLine("  export time. Treat them as opinion, not as extracted fact.");
        md.AppendLine();
        md.AppendLine("## Where things are");
        md.AppendLine();
        md.AppendLine("| File | Contents |");
        md.AppendLine("| --- | --- |");
        md.AppendLine("| `solution.json` | Everything: tables, columns, relationships, flows, roles, apps, env vars |");
        md.AppendLine("| `docs/index.md` | Overview and contents |");
        md.AppendLine("| `docs/tables/<name>.md` | One file per table: columns, requirement levels, relationships, forms, views |");
        md.AppendLine("| `docs/flows/<name>.md` | One file per cloud flow: trigger, steps, connectors |");
        md.AppendLine("| `docs/relationships.md` | Every declared and inferred relationship |");
        md.AppendLine("| `docs/solution-artefacts.md` | Automations, roles, apps, navigation, env vars, web resources |");
        md.AppendLine("| `manifest.json` | Counts and file map |");
        md.AppendLine();
        md.AppendLine($"Solution: {model.UniqueName} v{model.Version}, " +
                      $"{(model.IsManaged ? "managed" : "unmanaged")}, publisher {model.PublisherDisplayName}. " +
                      $"{model.Entities.Count} tables, {model.Processes.Count} processes.");
        return md.ToString();
    }

    private static string BuildSkill(SolutionModel model)
    {
        var md = new StringBuilder();
        md.AppendLine("---");
        md.AppendLine("name: solution-qa");
        md.AppendLine($"description: Answer questions about the {model.DisplayName} Power Platform solution from the Shieldsmith docpack in this folder. Use whenever the user asks what this solution does, how a table or flow works, what depends on what, or wants an impact assessment for a change.");
        md.AppendLine("---");
        md.AppendLine();
        md.AppendLine("# Answering questions about this solution");
        md.AppendLine();
        md.AppendLine("1. Start from `manifest.json` for counts and the file map, and `docs/index.md` for the");
        md.AppendLine("   overview. For anything detailed, prefer `solution.json`: it is the complete extraction.");
        md.AppendLine("2. For \"what uses X\" questions, search `solution.json` for the logical name: lookups");
        md.AppendLine("   appear in relationships, flow references appear under processes, form usage under the");
        md.AppendLine("   owning table's forms.");
        md.AppendLine("3. For impact assessments, list: relationships touching the table, flows whose trigger or");
        md.AppendLine("   actions reference it, forms and views on it, and security roles naming it. Only list");
        md.AppendLine("   what the files show; say explicitly that anything outside the solution (other solutions,");
        md.AppendLine("   reports, integrations) is not visible here.");
        md.AppendLine("4. Separate fact from inference. Facts cite a file. Inference (for example, guessing a");
        md.AppendLine("   table's business purpose from its name) is labelled as inference.");
        return md.ToString();
    }
}
