using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using Shieldsmith.Core.Models;
using A = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;

namespace Shieldsmith.Outputs.Word;

/// <summary>
/// Writes the solution documentation .docx: cover page, table of contents that
/// updates on open, per-table column and relationship detail, the embedded ERD
/// image, environment variables with joined values, and every parsing
/// diagnostic. The document is complete without any AI content.
/// </summary>
public static class WordReportBuilder
{
    private const long EmuPerInch = 914400L;
    private const double ContentWidthInches = 6.26; // A4 portrait minus 2.5 cm margins

    public static string Write(SolutionModel model, string outputPath, string? erdPngPath = null,
        GeneratedInterpretation? interpretation = null, Diagrams.DiagramSet? diagrams = null)
    {
        // A rendered diagram set supersedes a bare ERD path.
        erdPngPath = diagrams?.Erd?.PngPath ?? erdPngPath;
        if (!outputPath.EndsWith(".docx", StringComparison.OrdinalIgnoreCase))
            outputPath = Path.ChangeExtension(outputPath, ".docx");

        using var document = WordprocessingDocument.Create(outputPath, WordprocessingDocumentType.Document);
        var mainPart = document.AddMainDocumentPart();
        mainPart.Document = new Document();
        var body = mainPart.Document.AppendChild(new Body());

        WordStyles.AddTo(mainPart);
        AddUpdateFieldsSetting(document);
        var footerId = AddFooterWithPageNumbers(mainPart);

        // Cover page. The Heading1 style breaks the page before each section,
        // so no manual breaks are needed here or after the contents.
        body.Append(Styled(WordStyles.Title, model.DisplayName));
        body.Append(Styled(WordStyles.Subtitle, "Solution documentation"));
        body.Append(MutedText($"Solution unique name: {model.UniqueName}"));
        body.Append(MutedText($"Version {model.Version}  ·  {(model.IsManaged ? "Managed" : "Unmanaged")}  ·  " +
                              $"Publisher: {model.PublisherDisplayName}"));
        body.Append(MutedText($"Generated by Shieldsmith on {DateTime.Now:d MMMM yyyy} from the solution export file. " +
                              "Every fact in this document is read from the export itself."));

        // Table of contents.
        body.Append(Styled(WordStyles.Heading1, "Contents"));
        body.Append(TocField());

        // Overview.
        body.Append(Styled(WordStyles.Heading1, "Solution overview"));
        body.Append(KeyValueTable(new[]
        {
            ("Unique name", model.UniqueName),
            ("Display name", model.DisplayName),
            ("Version", model.Version),
            ("Type", model.IsManaged ? "Managed" : "Unmanaged"),
            ("Publisher", $"{model.PublisherDisplayName} ({model.PublisherUniqueName})"),
            ("Customisation prefix", model.CustomizationPrefix),
            ("Components", model.RootComponents.Count.ToString()),
            ("Tables", model.Entities.Count.ToString()),
            ("Relationships",
                $"{model.OneToManyRelationships.Count} one-to-many, {model.ManyToManyRelationships.Count} many-to-many"),
            ("Environment variables", model.EnvironmentVariables.Count.ToString()),
        }));

        if (interpretation?.SolutionOverview is not null)
            AppendAiBlock(body, interpretation, interpretation.SolutionOverview);

        // Component inventory grouped by type.
        body.Append(Styled(WordStyles.Heading1, "Component inventory"));
        var componentRows = new List<string[]> { new[] { "Component type", "Count", "Identifiers" } };
        foreach (var group in model.RootComponents.GroupBy(c => c.TypeName).OrderByDescending(g => g.Count()))
        {
            componentRows.Add(new[]
            {
                group.Key,
                group.Count().ToString(),
                string.Join(", ", group.Select(c => c.DisplayIdentifier).Take(20)) +
                    (group.Count() > 20 ? $" and {group.Count() - 20} more" : string.Empty),
            });
        }
        body.Append(DataTable(componentRows));

        // Data model diagram.
        if (erdPngPath is not null && File.Exists(erdPngPath))
        {
            body.Append(Styled(WordStyles.Heading1, "Entity relationship diagram"));
            AppendImage(mainPart, body, erdPngPath);
        }

        // Tables in detail.
        body.Append(Styled(WordStyles.Heading1, "Tables"));
        foreach (var entity in model.Entities.OrderBy(e => e.DisplayName, StringComparer.OrdinalIgnoreCase))
        {
            body.Append(Styled(WordStyles.Heading2,
                string.IsNullOrEmpty(entity.DisplayName) ? entity.SchemaName : entity.DisplayName));
            body.Append(Text($"Logical name: {entity.LogicalName}" +
                             (string.IsNullOrEmpty(entity.OwnershipType) ? string.Empty : $"  ·  Ownership: {entity.OwnershipType}") +
                             (entity.IsAuditEnabled ? "  ·  Auditing enabled" : string.Empty)));
            if (!string.IsNullOrEmpty(entity.Description))
                body.Append(Text(entity.Description));

            if (interpretation is not null
                && interpretation.EntityDescriptions.TryGetValue(entity.LogicalName, out var entityAi))
                AppendAiBlock(body, interpretation, entityAi);

            if (entity.Attributes.Count == 0)
            {
                body.Append(Text("This table is included in the solution without column metadata " +
                                 "(a ribbon or form-only change), so its columns are not part of this export."));
            }
            else
            {
                var attributeRows = new List<string[]> { new[] { "Column", "Logical name", "Type", "Requirement", "Notes" } };
                foreach (var attribute in entity.Attributes)
                {
                    var notes = new List<string>();
                    if (attribute.IsPrimaryId) notes.Add("Primary key");
                    if (attribute.IsPrimaryName) notes.Add("Primary name");
                    if (attribute.IsCustomField) notes.Add("Custom");
                    attributeRows.Add(new[]
                    {
                        attribute.DisplayName,
                        attribute.LogicalName,
                        attribute.TypeDisplay,
                        attribute.RequiredLevel.Display(),
                        string.Join(", ", notes),
                    });
                }
                body.Append(DataTable(attributeRows));
            }

            if (entity.Keys.Count > 0)
            {
                body.Append(Styled(WordStyles.Heading3, "Alternate keys"));
                var keyRows = new List<string[]> { new[] { "Key", "Columns" } };
                foreach (var key in entity.Keys)
                    keyRows.Add(new[] { key.DisplayName, string.Join(", ", key.KeyAttributes) });
                body.Append(DataTable(keyRows));
            }

            if (entity.Forms.Count > 0)
            {
                body.Append(Styled(WordStyles.Heading3, "Forms"));
                var formRows = new List<string[]> { new[] { "Form", "Type", "Tabs and sections", "Script libraries" } };
                foreach (var form in entity.Forms)
                {
                    var structure = string.Join("; ", form.Tabs.Select(t =>
                        $"{t.Label}: {string.Join(", ", t.Sections.Select(s => $"{s.Label} ({s.Fields.Count} fields)"))}"));
                    formRows.Add(new[] { form.Name, form.FormType, structure, string.Join(", ", form.Libraries) });
                }
                body.Append(DataTable(formRows));
            }

            if (entity.Views.Count > 0)
            {
                body.Append(Styled(WordStyles.Heading3, "Views"));
                var viewRows = new List<string[]> { new[] { "View", "Default", "Columns" } };
                foreach (var view in entity.Views)
                    viewRows.Add(new[] { view.Name, view.IsDefault ? "Yes" : "No", string.Join(", ", view.Columns) });
                body.Append(DataTable(viewRows));
            }
        }

        // Automations.
        if (model.Processes.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Automations"));
            var processRows = new List<string[]> { new[] { "Name", "Kind", "Primary table", "State" } };
            foreach (var process in model.Processes.OrderBy(p => p.KindDisplay).ThenBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
            {
                processRows.Add(new[]
                {
                    process.Name,
                    process.KindDisplay,
                    process.PrimaryEntity == "none" ? string.Empty : model.EntityDisplayName(process.PrimaryEntity),
                    process.IsActive ? "Active" : "Draft",
                });
            }
            body.Append(DataTable(processRows));

            foreach (var process in model.Processes.Where(p => p.CloudFlow is not null)
                         .OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
            {
                var flow = process.CloudFlow!;
                body.Append(Styled(WordStyles.Heading2, process.Name));
                if (flow.Trigger is not null)
                    body.Append(Text($"Trigger: {flow.Trigger.Summary}."));
                var connectors = flow.ConnectorsUsed.ToList();
                if (connectors.Count > 0)
                    body.Append(Text($"Connectors: {string.Join(", ", connectors)}."));

                if (interpretation is not null
                    && interpretation.FlowDescriptions.TryGetValue(process.Name, out var flowAi))
                    AppendAiBlock(body, interpretation, flowAi);

                if (diagrams is not null
                    && diagrams.FlowDiagrams.TryGetValue(process.Name, out var flowDiagram)
                    && flowDiagram.PngPath is not null
                    && File.Exists(flowDiagram.PngPath))
                {
                    AppendImage(mainPart, body, flowDiagram.PngPath);
                }

                var actionRows = new List<string[]> { new[] { "Step", "Operation" } };
                AppendActionRows(actionRows, flow.Actions, depth: 0);
                if (actionRows.Count > 1)
                    body.Append(DataTable(actionRows));
            }
        }

        // Canvas apps.
        if (model.CanvasApps.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Canvas apps"));
            foreach (var app in model.CanvasApps)
            {
                body.Append(Styled(WordStyles.Heading2, app.DisplayName));
                body.Append(Text($"{app.KindDisplay}, schema name {app.Name}" +
                                 (string.IsNullOrEmpty(app.AppVersion) ? string.Empty : $", version {app.AppVersion}") +
                                 (string.IsNullOrEmpty(app.FormFactor) ? string.Empty : $", {app.FormFactor}") + "."));
                if (!string.IsNullOrEmpty(app.Description)) body.Append(Text(app.Description));

                if (!app.HasInternals)
                {
                    body.Append(Text("The .msapp for this app is not present in the export, so only its " +
                                     "solution metadata is documented."));
                    continue;
                }

                if (app.DataSources.Count > 0)
                {
                    var rows = new List<string[]> { new[] { "Data source", "Table", "Entity set" } };
                    foreach (var source in app.DataSources)
                        rows.Add(new[] { source.Name, source.LogicalName, source.EntitySetName });
                    body.Append(DataTable(rows));
                }

                if (app.GlobalVariables.Count > 0 || app.Collections.Count > 0)
                {
                    body.Append(Text("Variables and collections below are derived from the app's formulas, " +
                                     "so they are inference rather than a declared list."));
                    if (app.GlobalVariables.Count > 0)
                        body.Append(Text($"Global variables: {string.Join(", ", app.GlobalVariables)}"));
                    if (app.Collections.Count > 0)
                        body.Append(Text($"Collections: {string.Join(", ", app.Collections)}"));
                }

                foreach (var screen in app.Screens)
                {
                    body.Append(Styled(WordStyles.Heading3, $"Screen: {screen.Name}"));
                    var rows = new List<string[]> { new[] { "Control", "Type", "Authored properties" } };
                    foreach (var control in screen.AllControls())
                    {
                        rows.Add(new[]
                        {
                            control.Name,
                            control.Type,
                            string.Join("; ", control.Properties.Select(p => $"{p.Key} = {Shorten(p.Value)}")),
                        });
                    }
                    body.Append(DataTable(rows));
                }
            }
        }

        // Copilot Studio agents.
        if (model.Agents.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Agents"));
            foreach (var agent in model.Agents)
            {
                body.Append(Styled(WordStyles.Heading2, agent.Name));
                body.Append(Text($"Schema name {agent.SchemaName}, {agent.AuthenticationModeDisplay}" +
                                 (agent.GenerativeActionsEnabled ? ", generative actions enabled" : string.Empty) + "."));
                if (!string.IsNullOrEmpty(agent.Instructions))
                {
                    body.Append(Styled(WordStyles.Heading3, "Instructions"));
                    foreach (var line in agent.Instructions.Split('\n'))
                        body.Append(Text(line));
                }

                if (agent.Topics.Count > 0)
                {
                    body.Append(Styled(WordStyles.Heading3, "Topics"));
                    var rows = new List<string[]> { new[] { "Topic", "Trigger phrases", "Messages" } };
                    foreach (var topic in agent.Topics)
                    {
                        rows.Add(new[]
                        {
                            topic.DisplayName,
                            string.Join("; ", topic.TriggerQueries),
                            string.Join(" | ", topic.Messages),
                        });
                    }
                    body.Append(DataTable(rows));
                }

                if (agent.Tools.Count > 0)
                {
                    body.Append(Styled(WordStyles.Heading3, "Tools"));
                    var rows = new List<string[]> { new[] { "Tool", "Kind", "Description" } };
                    foreach (var tool in agent.Tools)
                        rows.Add(new[] { tool.Name, tool.Kind, tool.Description });
                    body.Append(DataTable(rows));
                }

                if (agent.KnowledgeSources.Count > 0)
                {
                    body.Append(Styled(WordStyles.Heading3, "Knowledge sources"));
                    var rows = new List<string[]> { new[] { "Source", "Kind", "Location" } };
                    foreach (var source in agent.KnowledgeSources)
                        rows.Add(new[] { source.Name, source.SourceKind, source.Site });
                    body.Append(DataTable(rows));
                }
            }
        }

        // Business process flows: the stage list, which exists nowhere else
        // outside the designer.
        var businessProcessFlows = model.Processes.Where(p => p.BusinessProcessFlow is not null).ToList();
        if (businessProcessFlows.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Business process flows"));
            foreach (var process in businessProcessFlows)
            {
                var detail = process.BusinessProcessFlow!;
                body.Append(Styled(WordStyles.Heading2, process.Name));
                body.Append(Text($"{(process.IsActive ? "Active" : "Draft")}. Runs on {process.PrimaryEntity}. " +
                                 $"{detail.Stages.Count} stages, {detail.StepCount} steps."));

                var rows = new List<string[]> { new[] { "#", "Stage", "Steps" } };
                foreach (var stage in detail.Stages)
                {
                    var steps = stage.Steps.Count == 0
                        ? "none"
                        : string.Join(", ", stage.Steps.Select(s =>
                            s.DataField.Length > 0 ? $"{s.Name} ({s.DataField})" : s.Name));
                    rows.Add(new[] { stage.Order.ToString(), stage.Name, steps });
                }
                body.Append(DataTable(rows));
            }
        }

        // Plugins. Nothing else that reads an export documents these.
        if (model.PluginAssemblies.Count > 0 || model.SdkMessageSteps.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Plugins"));
            foreach (var assembly in model.PluginAssemblies)
            {
                body.Append(Styled(WordStyles.Heading2, assembly.Name));
                body.Append(Text($"Version {assembly.Version}. Isolation: {assembly.IsolationMode}. " +
                                 $"{assembly.Types.Count} type(s)."));
                if (assembly.Types.Count > 0)
                    body.Append(Text("Types: " + string.Join(", ", assembly.Types.Select(t => t.DisplayName))));
                AppendPluginSteps(body, assembly.Steps);
            }

            var unowned = model.SdkMessageSteps
                .Where(s => !model.PluginAssemblies.Any(a => a.Steps.Contains(s))).ToList();
            if (unowned.Count > 0)
            {
                body.Append(Styled(WordStyles.Heading2,
                    "Registrations whose assembly is not in this solution"));
                body.Append(Text("These steps run against this solution's tables, but the code that " +
                                 "implements them ships elsewhere."));
                AppendPluginSteps(body, unowned);
            }
        }

        // Desktop flows.
        var desktopFlows = model.Processes.Where(p => p.DesktopFlow is not null).ToList();
        if (desktopFlows.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Desktop flows"));
            foreach (var process in desktopFlows)
            {
                var detail = process.DesktopFlow!;
                body.Append(Styled(WordStyles.Heading2, process.Name));
                body.Append(Text($"{(process.IsActive ? "Active" : "Draft")}" +
                                 (string.IsNullOrEmpty(detail.SchemaVersion) ? string.Empty : $", schema {detail.SchemaVersion}") +
                                 $". {detail.TotalSteps} steps across {detail.Subflows.Count} subflows."));
                if (detail.Modules.Count > 0)
                    body.Append(Text($"Modules used: {string.Join(", ", detail.Modules)}."));

                if (detail.Inputs.Count > 0 || detail.Outputs.Count > 0)
                {
                    var rows = new List<string[]> { new[] { "Direction", "Name", "Type", "Description" } };
                    foreach (var input in detail.Inputs)
                        rows.Add(new[] { "Input", input.Name, input.Type, input.Description });
                    foreach (var output in detail.Outputs)
                        rows.Add(new[] { "Output", output.Name, output.Type, output.Description });
                    body.Append(DataTable(rows));
                }

                foreach (var subflow in detail.Subflows.Where(s => s.Steps.Count > 0))
                {
                    body.Append(Styled(WordStyles.Heading3,
                        subflow.Name + (subflow.IsGlobal ? " (global)" : string.Empty)));
                    var rows = new List<string[]> { new[] { "Step", "Outputs" } };
                    foreach (var step in subflow.Steps)
                    {
                        rows.Add(new[]
                        {
                            new string(' ', step.Depth * 4) + step.Action +
                                (step.IsDisabled ? "  [disabled]" : string.Empty),
                            string.Join(", ", step.OutputVariables),
                        });
                    }
                    body.Append(DataTable(rows));
                }
            }
        }

        // Option sets.
        if (model.OptionSets.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Choices (option sets)"));
            var optionRows = new List<string[]> { new[] { "Name", "Display name", "Scope", "Values" } };
            foreach (var optionSet in model.OptionSets)
            {
                optionRows.Add(new[]
                {
                    optionSet.Name,
                    optionSet.DisplayName,
                    optionSet.IsGlobal ? "Global" : "Local",
                    string.Join(", ", optionSet.Options.Select(o => o.Label)),
                });
            }
            body.Append(DataTable(optionRows));
        }

        // Security roles.
        if (model.SecurityRoles.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Security roles"));
            var roleRows = new List<string[]> { new[] { "Role", "Privileges", "By level" } };
            foreach (var role in model.SecurityRoles.OrderBy(r => r.Name, StringComparer.OrdinalIgnoreCase))
            {
                roleRows.Add(new[]
                {
                    role.Name,
                    role.Privileges.Count.ToString(),
                    string.Join(", ", role.PrivilegeCountsByLevel.OrderBy(kv => kv.Key).Select(kv => $"{kv.Key}: {kv.Value}")),
                });
            }
            body.Append(DataTable(roleRows));
        }

        // Model-driven apps and navigation.
        if (model.AppModules.Count > 0 || model.SiteMaps.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Apps and navigation"));
            if (model.AppModules.Count > 0)
            {
                var appRows = new List<string[]> { new[] { "App", "Unique name", "Components" } };
                foreach (var app in model.AppModules)
                    appRows.Add(new[] { app.Name, app.UniqueName, app.ComponentCount.ToString() });
                body.Append(DataTable(appRows));
            }
            foreach (var siteMap in model.SiteMaps)
            {
                body.Append(Styled(WordStyles.Heading2, $"Navigation: {siteMap.UniqueName}"));
                foreach (var area in siteMap.Areas)
                {
                    foreach (var group in area.Groups)
                    {
                        var items = string.Join(", ", group.SubAreas.Select(sa =>
                            string.IsNullOrEmpty(sa.Entity) ? sa.Title : $"{sa.Title} ({sa.Entity})"));
                        body.Append(Text($"{area.Title} > {group.Title}: {items}"));
                    }
                }
            }
        }

        // Web resources.
        if (model.WebResources.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Web resources"));
            var resourceRows = new List<string[]> { new[] { "Name", "Display name", "Type" } };
            foreach (var resource in model.WebResources.OrderBy(r => r.Name, StringComparer.OrdinalIgnoreCase))
                resourceRows.Add(new[] { resource.Name, resource.DisplayName, resource.TypeName });
            body.Append(DataTable(resourceRows));
        }

        // Connection references.
        if (model.ConnectionReferences.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Connection references"));
            var referenceRows = new List<string[]> { new[] { "Logical name", "Display name", "Connector" } };
            foreach (var reference in model.ConnectionReferences.OrderBy(r => r.LogicalName, StringComparer.OrdinalIgnoreCase))
                referenceRows.Add(new[] { reference.LogicalName, reference.DisplayName, reference.ConnectorShortName });
            body.Append(DataTable(referenceRows));
        }

        // Relationships.
        body.Append(Styled(WordStyles.Heading1, "Relationships"));
        if (model.OneToManyRelationships.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading2, "One-to-many"));
            var rows = new List<string[]> { new[] { "Relationship", "One", "Many", "Lookup column", "Cascade delete" } };
            foreach (var relationship in model.OneToManyRelationships.OrderBy(r => r.SchemaName, StringComparer.OrdinalIgnoreCase))
            {
                rows.Add(new[]
                {
                    relationship.SchemaName,
                    model.EntityDisplayName(relationship.ReferencedEntity),
                    model.EntityDisplayName(relationship.ReferencingEntity),
                    relationship.ReferencingAttribute,
                    relationship.CascadeDelete,
                });
            }
            body.Append(DataTable(rows));
        }
        if (model.ManyToManyRelationships.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading2, "Many-to-many"));
            var rows = new List<string[]> { new[] { "Relationship", "Table 1", "Table 2", "Intersect table" } };
            foreach (var relationship in model.ManyToManyRelationships.OrderBy(r => r.SchemaName, StringComparer.OrdinalIgnoreCase))
            {
                rows.Add(new[]
                {
                    relationship.SchemaName,
                    model.EntityDisplayName(relationship.Entity1),
                    model.EntityDisplayName(relationship.Entity2),
                    relationship.IntersectEntity,
                });
            }
            body.Append(DataTable(rows));
        }
        if (model.InferredLookups.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading2, "Implicit lookup relationships"));
            body.Append(Text("These relationships are inferred from lookup-shaped columns (owner, customer, " +
                             "party list, or lookups whose declared relationship is outside this solution). " +
                             "They are inference, not declared fact, and are listed separately for that reason."));
            var rows = new List<string[]> { new[] { "Table", "Column", "Column type" } };
            foreach (var lookup in model.InferredLookups.OrderBy(l => l.Entity, StringComparer.OrdinalIgnoreCase))
                rows.Add(new[] { model.EntityDisplayName(lookup.Entity), lookup.AttributeLogicalName, lookup.AttributeType });
            body.Append(DataTable(rows));
        }

        // Environment variables.
        if (model.EnvironmentVariables.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Environment variables"));
            var rows = new List<string[]> { new[] { "Name", "Display name", "Type", "Required", "Default value", "Current value" } };
            foreach (var variable in model.EnvironmentVariables)
            {
                rows.Add(new[]
                {
                    variable.SchemaName,
                    variable.DisplayName,
                    variable.TypeName,
                    variable.IsRequired ? "Yes" : "No",
                    variable.IsSecret ? "[secret]" : variable.DefaultValue,
                    variable.IsSecret ? "[secret]" : variable.HasCurrentValue ? variable.CurrentValue : "(not in export)",
                });
            }
            body.Append(DataTable(rows));
        }

        // AI risk observations, clearly separated from extracted fact.
        if (interpretation?.RiskObservations is not null || interpretation?.Notes.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "AI observations"));
            body.Append(Text("This section is generated interpretation, not extracted fact. The rest of " +
                             "this document is complete without it."));
            if (interpretation.RiskObservations is not null)
                AppendAiBlock(body, interpretation, interpretation.RiskObservations);
            foreach (var note in interpretation.Notes)
                body.Append(Text(note));
        }

        // Diagram notes: which engine drew what, and anything that was capped.
        if (diagrams is not null && diagrams.Notes.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Diagram notes"));
            foreach (var note in diagrams.Notes) body.Append(Text(note));
        }

        // Diagnostics: what the parser could not fully read, stated plainly.
        if (model.Diagnostics.Count > 0)
        {
            body.Append(Styled(WordStyles.Heading1, "Parsing notes"));
            body.Append(Text("The following was observed while reading the export. Nothing here has been guessed at or filled in."));
            foreach (var diagnostic in model.Diagnostics)
                body.Append(Text($"{diagnostic.Severity}: {diagnostic.Message}"));
        }

        // Section properties: A4, margins, footer with page number. TitlePage
        // gives the cover a blank first-page footer, so numbering visibly
        // starts on the contents page rather than stamping "1" on the cover.
        body.Append(new SectionProperties(
            new FooterReference { Type = HeaderFooterValues.Default, Id = footerId },
            new PageSize { Width = 11906, Height = 16838 },
            new PageMargin { Top = 1418, Bottom = 1418, Left = 1418, Right = 1418, Footer = 709 },
            new TitlePage()));

        mainPart.Document.Save();
        return outputPath;
    }

    /// <summary>
    /// Renders AI text in a visually distinct block: shaded, bordered, and
    /// captioned with provider, model and date. Never used for extracted facts.
    /// </summary>
    private static void AppendAiBlock(Body body, GeneratedInterpretation interpretation, string text)
    {
        body.Append(new Paragraph(
            AiBlockProperties(),
            new Run(
                new RunProperties(new Italic(), new Color { Val = "595959" },
                    new FontSize { Val = "16" }),
                new Text(interpretation.Attribution) { Space = SpaceProcessingModeValues.Preserve })));

        foreach (var paragraphText in text.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            body.Append(new Paragraph(
                AiBlockProperties(),
                new Run(new Text(paragraphText.TrimEnd()) { Space = SpaceProcessingModeValues.Preserve })));
        }
    }

    private static ParagraphProperties AiBlockProperties() =>
        new(
            new ParagraphBorders(
                new LeftBorder { Val = BorderValues.Single, Size = 18, Color = WordStyles.Accent }),
            new Shading { Val = ShadingPatternValues.Clear, Fill = WordStyles.AccentTint },
            new Indentation { Left = "240" });

    private static void AppendActionRows(List<string[]> rows, IEnumerable<FlowAction> actions, int depth)
    {
        foreach (var action in actions)
        {
            var indent = new string(' ', depth * 4);
            rows.Add(new[] { indent + action.DisplayName, action.OperationDisplay });

            // Each branch gets a heading row, so a condition's Yes and No paths
            // are distinguishable rather than one undifferentiated list.
            foreach (var branch in action.Branches)
            {
                var childDepth = depth + 1;
                if (branch.Label.Length > 0)
                {
                    rows.Add(new[] { new string(' ', childDepth * 4) + branch.Label, string.Empty });
                    childDepth++;
                }
                AppendActionRows(rows, branch.Actions, childDepth);
            }
        }
    }

    private static void AddUpdateFieldsSetting(WordprocessingDocument document)
    {
        var settingsPart = document.MainDocumentPart!.AddNewPart<DocumentSettingsPart>();
        settingsPart.Settings = new Settings(new UpdateFieldsOnOpen { Val = true });
        settingsPart.Settings.Save();
    }

    private static string AddFooterWithPageNumbers(MainDocumentPart mainPart)
    {
        var footerPart = mainPart.AddNewPart<FooterPart>();
        footerPart.Footer = new Footer(
            new Paragraph(
                new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
                new SimpleField { Instruction = "PAGE" }));
        footerPart.Footer.Save();
        return mainPart.GetIdOfPart(footerPart);
    }

    private static Paragraph TocField() =>
        new(
            new Run(new FieldChar { FieldCharType = FieldCharValues.Begin }),
            new Run(new FieldCode(" TOC \\o \"1-2\" \\h \\z \\u ") { Space = SpaceProcessingModeValues.Preserve }),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Separate }),
            new Run(new Text("The table of contents fills in when the document is opened in Word.")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.End }));

    /// <summary>Trims a formula so a table cell stays readable.</summary>
    private static string Shorten(string text, int length = 90)
    {
        var single = text.Replace('\n', ' ').Replace('\r', ' ').Trim();
        return single.Length <= length ? single : single[..length] + "...";
    }

    private static Paragraph Styled(string styleId, string text) =>
        new(new ParagraphProperties(new ParagraphStyleId { Val = styleId }),
            new Run(new Text(text) { Space = SpaceProcessingModeValues.Preserve }));

    private static Paragraph Text(string text) =>
        new(new Run(new Text(text) { Space = SpaceProcessingModeValues.Preserve }));

    private static Paragraph MutedText(string text) =>
        new(new Run(
            new RunProperties(new Color { Val = WordStyles.MutedText }),
            new Text(text) { Space = SpaceProcessingModeValues.Preserve }));

    private static Paragraph PageBreak() =>
        new(new Run(new Break { Type = BreakValues.Page }));

    private static Table KeyValueTable(IReadOnlyList<(string Key, string Value)> pairs)
    {
        var table = NewTable(2);
        foreach (var (key, value) in pairs)
        {
            table.Append(new TableRow(
                BoldCell(key),
                PlainCell(value)));
        }
        return table;
    }

    private static Table DataTable(IReadOnlyList<string[]> rows)
    {
        var table = NewTable(rows[0].Length);
        for (var i = 0; i < rows.Count; i++)
        {
            var row = new TableRow();
            if (i == 0) row.Append(new TableRowProperties(new TableHeader()));
            // Banded rows: a long attribute table is read a row at a time, and
            // the tint is what stops the eye slipping a line.
            var band = i > 0 && i % 2 == 0 ? WordStyles.BandTint : null;
            foreach (var cellText in rows[i])
                row.Append(i == 0 ? HeaderCell(cellText) : PlainCell(cellText, band));
            table.Append(row);
        }
        return table;
    }

    private static Table NewTable(int columnCount)
    {
        var grid = new TableGrid();
        for (var i = 0; i < columnCount; i++)
            grid.Append(new GridColumn());
        return new Table(
            new TableProperties(
                new TableStyle { Val = WordStyles.TableStyle },
                new TableWidth { Width = "5000", Type = TableWidthUnitValues.Pct },
                new TableLayout { Type = TableLayoutValues.Autofit }),
            grid);
    }

    /// <summary>Cell paragraphs drop the document's after-spacing; inherited
    /// paragraph gaps inside table cells make every row needlessly tall.</summary>
    private static ParagraphProperties CellParagraphProperties() =>
        new(new SpacingBetweenLines { After = "0" });

    private static TableCell HeaderCell(string text) =>
        new(new TableCellProperties(
                new Shading { Val = ShadingPatternValues.Clear, Fill = WordStyles.Accent },
                new TableCellVerticalAlignment { Val = TableVerticalAlignmentValues.Center }),
            new Paragraph(
                CellParagraphProperties(),
                new Run(
                    new RunProperties(new Bold(), new Color { Val = "FFFFFF" }),
                    new Text(text) { Space = SpaceProcessingModeValues.Preserve })));

    private static TableCell BoldCell(string text) =>
        new(new TableCellProperties(
                new Shading { Val = ShadingPatternValues.Clear, Fill = WordStyles.BandTint }),
            new Paragraph(
                CellParagraphProperties(),
                new Run(
                    new RunProperties(new Bold()),
                    new Text(text) { Space = SpaceProcessingModeValues.Preserve })));

    private static TableCell PlainCell(string text, string? shading = null)
    {
        var cell = new TableCell(new Paragraph(
            CellParagraphProperties(),
            new Run(new Text(text) { Space = SpaceProcessingModeValues.Preserve })));
        if (shading is not null)
            cell.PrependChild(new TableCellProperties(
                new Shading { Val = ShadingPatternValues.Clear, Fill = shading }));
        return cell;
    }

    private static void AppendPluginSteps(Body body, IReadOnlyCollection<SdkMessageStepModel> steps)
    {
        if (steps.Count == 0)
        {
            body.Append(Text("No registered steps in this solution."));
            return;
        }

        var rows = new List<string[]>
        {
            new[] { "Message", "Table", "Stage", "Mode", "Rank", "Filtering columns" },
        };
        foreach (var step in steps.OrderBy(s => s.PrimaryEntity).ThenBy(s => s.Rank))
        {
            // The export carries a message GUID, not a name. Where the name
            // could not be recovered this says so rather than leaving a blank
            // cell that reads as "no message".
            rows.Add(new[]
            {
                step.Message.Length > 0 ? step.Message : "not stated in the export",
                step.PrimaryEntity,
                step.Stage,
                step.Mode,
                step.Rank.ToString(),
                step.FilteringAttributes.Count > 0
                    ? string.Join(", ", step.FilteringAttributes)
                    : "all columns",
            });
        }
        body.Append(DataTable(rows));
    }

    private static void AppendImage(MainDocumentPart mainPart, Body body, string pngPath)
    {
        double widthInches, heightInches;
        using (var image = System.Drawing.Image.FromFile(pngPath))
        {
            widthInches = image.Width / (double)image.HorizontalResolution;
            heightInches = image.Height / (double)image.VerticalResolution;
        }

        // Fit to the text column, and cap height so a tall flow chart does not
        // run off the page.
        var scale = Math.Min(1.0, ContentWidthInches / widthInches);
        const double maxHeightInches = 8.2;
        if (heightInches * scale > maxHeightInches)
            scale = maxHeightInches / heightInches;
        var cx = (long)(widthInches * scale * EmuPerInch);
        var cy = (long)(heightInches * scale * EmuPerInch);

        var imagePart = mainPart.AddImagePart(ImagePartType.Png);
        using (var stream = File.OpenRead(pngPath))
            imagePart.FeedData(stream);
        var relationshipId = mainPart.GetIdOfPart(imagePart);

        // Drawing ids must be unique within the document; the part count gives a
        // fresh number per image without a static counter shared across writes.
        var drawingId = (uint)mainPart.ImageParts.Count();

        var drawing = new Drawing(
            new DW.Inline(
                new DW.Extent { Cx = cx, Cy = cy },
                new DW.DocProperties { Id = drawingId, Name = $"Diagram {drawingId}" },
                new A.Graphic(
                    new A.GraphicData(
                        new PIC.Picture(
                            new PIC.NonVisualPictureProperties(
                                new PIC.NonVisualDrawingProperties { Id = drawingId, Name = Path.GetFileName(pngPath) },
                                new PIC.NonVisualPictureDrawingProperties()),
                            new PIC.BlipFill(
                                new A.Blip { Embed = relationshipId },
                                new A.Stretch(new A.FillRectangle())),
                            new PIC.ShapeProperties(
                                new A.Transform2D(
                                    new A.Offset { X = 0L, Y = 0L },
                                    new A.Extents { Cx = cx, Cy = cy }),
                                new A.PresetGeometry(new A.AdjustValueList()) { Preset = A.ShapeTypeValues.Rectangle })))
                    { Uri = "http://schemas.openxmlformats.org/drawingml/2006/picture" }))
            { DistanceFromTop = 0U, DistanceFromBottom = 0U, DistanceFromLeft = 0U, DistanceFromRight = 0U });

        body.Append(new Paragraph(new Run(drawing)));
    }
}
