using System.Text;
using Shieldsmith.Core.Models;

namespace Shieldsmith.Outputs.Markdown;

/// <summary>
/// Writes the documentation as a folder of Markdown files: an index, one file
/// per table, one per cloud flow, and one each for the cross-cutting artefacts.
/// The content mirrors the Word report, which makes this suitable for GitHub or
/// Azure DevOps wikis and reusable as the bulk of the Claude Code export pack.
/// </summary>
public static class MarkdownReportBuilder
{
    public static string Write(SolutionModel model, string outputDirectory, string? erdPngPath = null,
        GeneratedInterpretation? interpretation = null, Diagrams.DiagramSet? diagrams = null)
    {
        erdPngPath = diagrams?.Erd?.PngPath ?? erdPngPath;
        Directory.CreateDirectory(outputDirectory);
        var entitiesDir = Path.Combine(outputDirectory, "tables");
        var flowsDir = Path.Combine(outputDirectory, "flows");
        Directory.CreateDirectory(entitiesDir);
        Directory.CreateDirectory(flowsDir);

        string? erdFileName = null;
        if (erdPngPath is not null && File.Exists(erdPngPath))
        {
            erdFileName = "erd.png";
            File.Copy(erdPngPath, Path.Combine(outputDirectory, erdFileName), overwrite: true);
        }

        WriteIndex(model, outputDirectory, erdFileName, interpretation, diagrams);
        foreach (var entity in model.Entities)
            WriteEntity(model, entity, entitiesDir, interpretation);
        foreach (var process in model.Processes.Where(p => p.CloudFlow is not null))
            WriteFlow(process, flowsDir, interpretation, diagrams);
        WriteComponents(model, outputDirectory);
        WriteRelationships(model, outputDirectory);
        WriteCrossCutting(model, outputDirectory);

        return outputDirectory;
    }

    private static void WriteIndex(SolutionModel model, string dir, string? erdFileName,
        GeneratedInterpretation? interpretation, Diagrams.DiagramSet? diagrams)
    {
        var md = new StringBuilder();
        md.AppendLine($"# {model.DisplayName}");
        md.AppendLine();
        md.AppendLine($"Solution documentation generated by Shieldsmith from the export file. " +
                      "Every fact here is read from the export itself.");
        md.AppendLine();
        md.AppendLine($"| | |");
        md.AppendLine($"| --- | --- |");
        md.AppendLine($"| Unique name | {model.UniqueName} |");
        md.AppendLine($"| Version | {model.Version} |");
        md.AppendLine($"| Type | {(model.IsManaged ? "Managed" : "Unmanaged")} |");
        md.AppendLine($"| Publisher | {model.PublisherDisplayName} ({model.PublisherUniqueName}) |");
        md.AppendLine($"| Components | {model.RootComponents.Count} |");
        md.AppendLine($"| Tables | {model.Entities.Count} |");
        md.AppendLine($"| Relationships | {model.OneToManyRelationships.Count} one-to-many, {model.ManyToManyRelationships.Count} many-to-many |");
        md.AppendLine();

        if (interpretation?.SolutionOverview is not null)
            AppendAiBlock(md, interpretation, interpretation.SolutionOverview);

        if (interpretation?.RiskObservations is not null)
        {
            md.AppendLine("## AI observations");
            md.AppendLine();
            md.AppendLine("This section is generated interpretation, not extracted fact.");
            md.AppendLine();
            AppendAiBlock(md, interpretation, interpretation.RiskObservations);
            foreach (var note in interpretation.Notes)
                md.AppendLine($"- {Escape(note)}");
            md.AppendLine();
        }

        if (erdFileName is not null || !string.IsNullOrEmpty(diagrams?.ErdMermaidSource))
        {
            md.AppendLine("## Entity relationship diagram");
            md.AppendLine();
            // A mermaid fenced block renders natively on GitHub and Azure DevOps,
            // so the wiki shows a live diagram rather than a flat picture.
            if (!string.IsNullOrEmpty(diagrams?.ErdMermaidSource))
            {
                md.AppendLine("```mermaid");
                md.Append(diagrams.ErdMermaidSource.TrimEnd());
                md.AppendLine();
                md.AppendLine("```");
                md.AppendLine();
            }
            if (erdFileName is not null)
            {
                md.AppendLine($"![Entity relationship diagram]({erdFileName})");
                md.AppendLine();
            }
        }

        md.AppendLine("## Contents");
        md.AppendLine();
        md.AppendLine("- [Component inventory](components.md)");
        md.AppendLine("- [Relationships](relationships.md)");
        md.AppendLine("- [Automations, roles, apps and settings](solution-artefacts.md)");
        md.AppendLine();
        md.AppendLine("### Tables");
        md.AppendLine();
        foreach (var entity in model.Entities.OrderBy(e => e.DisplayName, StringComparer.OrdinalIgnoreCase))
            md.AppendLine($"- [{Display(entity)}](tables/{FileName(entity.LogicalName)}.md)");
        var flows = model.Processes.Where(p => p.CloudFlow is not null).ToList();
        if (flows.Count > 0)
        {
            md.AppendLine();
            md.AppendLine("### Cloud flows");
            md.AppendLine();
            foreach (var process in flows.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"- [{process.Name}](flows/{FileName(process.Name)}.md)");
        }

        if (model.Diagnostics.Count > 0)
        {
            md.AppendLine();
            md.AppendLine("## Parsing notes");
            md.AppendLine();
            foreach (var diagnostic in model.Diagnostics)
                md.AppendLine($"- {diagnostic.Severity}: {Escape(diagnostic.Message)}");
        }

        File.WriteAllText(Path.Combine(dir, "index.md"), md.ToString());
    }

    private static void WriteEntity(SolutionModel model, EntityModel entity, string dir,
        GeneratedInterpretation? interpretation = null)
    {
        var md = new StringBuilder();
        md.AppendLine($"# {Display(entity)}");
        md.AppendLine();
        md.AppendLine($"Logical name `{entity.LogicalName}`" +
                      (string.IsNullOrEmpty(entity.OwnershipType) ? string.Empty : $", {entity.OwnershipType}") +
                      (entity.IsAuditEnabled ? ", auditing enabled" : string.Empty) + ".");
        if (!string.IsNullOrEmpty(entity.Description))
        {
            md.AppendLine();
            md.AppendLine(Escape(entity.Description));
        }
        md.AppendLine();

        if (interpretation is not null
            && interpretation.EntityDescriptions.TryGetValue(entity.LogicalName, out var entityAi))
            AppendAiBlock(md, interpretation, entityAi);

        if (entity.Attributes.Count == 0)
        {
            md.AppendLine("This table is included without column metadata (a ribbon or form-only change).");
        }
        else
        {
            md.AppendLine("## Columns");
            md.AppendLine();
            md.AppendLine("| Column | Logical name | Type | Requirement | Notes |");
            md.AppendLine("| --- | --- | --- | --- | --- |");
            foreach (var attribute in entity.Attributes)
            {
                var notes = new List<string>();
                if (attribute.IsPrimaryId) notes.Add("Primary key");
                if (attribute.IsPrimaryName) notes.Add("Primary name");
                if (attribute.IsCustomField) notes.Add("Custom");
                md.AppendLine($"| {Escape(attribute.DisplayName)} | `{attribute.LogicalName}` | {attribute.TypeDisplay} " +
                              $"| {attribute.RequiredLevel.Display()} | {string.Join(", ", notes)} |");
            }
        }

        var oneToMany = model.OneToManyRelationships
            .Where(r => Matches(r.ReferencedEntity, entity) || Matches(r.ReferencingEntity, entity)).ToList();
        var manyToMany = model.ManyToManyRelationships
            .Where(r => Matches(r.Entity1, entity) || Matches(r.Entity2, entity)).ToList();
        if (oneToMany.Count > 0 || manyToMany.Count > 0)
        {
            md.AppendLine();
            md.AppendLine("## Relationships");
            md.AppendLine();
            foreach (var relationship in oneToMany)
                md.AppendLine($"- One {model.EntityDisplayName(relationship.ReferencedEntity)} to many " +
                              $"{model.EntityDisplayName(relationship.ReferencingEntity)} " +
                              $"(`{relationship.SchemaName}`, lookup `{relationship.ReferencingAttribute}`)");
            foreach (var relationship in manyToMany)
                md.AppendLine($"- Many {model.EntityDisplayName(relationship.Entity1)} to many " +
                              $"{model.EntityDisplayName(relationship.Entity2)} " +
                              $"through `{relationship.IntersectEntity}`");
        }

        if (entity.Forms.Count > 0)
        {
            md.AppendLine();
            md.AppendLine("## Forms");
            md.AppendLine();
            foreach (var form in entity.Forms)
            {
                md.AppendLine($"### {Escape(form.Name)} ({form.FormType})");
                md.AppendLine();
                foreach (var tab in form.Tabs)
                    foreach (var section in tab.Sections)
                        md.AppendLine($"- {Escape(tab.Label)} > {Escape(section.Label)}: " +
                                      string.Join(", ", section.Fields.Select(f => $"`{f}`")));
                if (form.Libraries.Count > 0)
                    md.AppendLine($"- Script libraries: {string.Join(", ", form.Libraries.Select(l => $"`{l}`"))}");
                md.AppendLine();
            }
        }

        if (entity.Views.Count > 0)
        {
            md.AppendLine("## Views");
            md.AppendLine();
            md.AppendLine("| View | Default | Columns |");
            md.AppendLine("| --- | --- | --- |");
            foreach (var view in entity.Views)
                md.AppendLine($"| {Escape(view.Name)} | {(view.IsDefault ? "Yes" : "No")} | " +
                              string.Join(", ", view.Columns.Select(c => $"`{c}`")) + " |");
        }

        File.WriteAllText(Path.Combine(dir, FileName(entity.LogicalName) + ".md"), md.ToString());
    }

    private static void WriteFlow(ProcessModel process, string dir,
        GeneratedInterpretation? interpretation = null, Diagrams.DiagramSet? diagrams = null)
    {
        var flow = process.CloudFlow!;
        var md = new StringBuilder();
        md.AppendLine($"# {process.Name}");
        md.AppendLine();
        md.AppendLine($"Cloud flow, {(process.IsActive ? "active" : "draft")}.");
        md.AppendLine();
        if (flow.Trigger is not null)
            md.AppendLine($"**Trigger:** {flow.Trigger.Summary}.");
        var connectors = flow.ConnectorsUsed.ToList();
        if (connectors.Count > 0)
            md.AppendLine($"**Connectors:** {string.Join(", ", connectors)}.");
        md.AppendLine();

        if (interpretation is not null
            && interpretation.FlowDescriptions.TryGetValue(process.Name, out var flowAi))
            AppendAiBlock(md, interpretation, flowAi);

        if (diagrams is not null
            && diagrams.FlowMermaidSources.TryGetValue(process.Name, out var flowMermaid))
        {
            md.AppendLine("## Diagram");
            md.AppendLine();
            // Renders live on GitHub and Azure DevOps.
            md.AppendLine("```mermaid");
            md.Append(flowMermaid.TrimEnd());
            md.AppendLine();
            md.AppendLine("```");
            md.AppendLine();
        }

        md.AppendLine("## Steps");
        md.AppendLine();
        AppendActions(md, flow.Actions, 0);
        File.WriteAllText(Path.Combine(dir, FileName(process.Name) + ".md"), md.ToString());
    }

    private static void AppendSteps(StringBuilder md, IReadOnlyCollection<SdkMessageStepModel> steps)
    {
        if (steps.Count == 0)
        {
            md.AppendLine("No registered steps in this solution.");
            md.AppendLine();
            return;
        }

        md.AppendLine("| Message | Table | Stage | Mode | Rank | Filtering columns |");
        md.AppendLine("| --- | --- | --- | --- | --- | --- |");
        foreach (var step in steps.OrderBy(s => s.PrimaryEntity).ThenBy(s => s.Rank))
        {
            // An empty message is a fact about the export, not a formatting gap.
            var message = step.Message.Length > 0 ? Escape(step.Message) : "*not in the export*";
            var filtering = step.FilteringAttributes.Count > 0
                ? string.Join(", ", step.FilteringAttributes.Select(a => $"`{a}`"))
                : "all columns";
            md.AppendLine($"| {message} | `{step.PrimaryEntity}` | {step.Stage} | {step.Mode} | " +
                          $"{step.Rank} | {filtering} |");
        }
        md.AppendLine();
    }

    private static void AppendActions(StringBuilder md, IEnumerable<FlowAction> actions, int depth)
    {
        foreach (var action in actions)
        {
            md.AppendLine($"{new string(' ', depth * 2)}- {Escape(action.DisplayName)}" +
                          (string.IsNullOrEmpty(action.OperationDisplay) ? string.Empty : $" — {action.OperationDisplay}"));
            AppendActions(md, action.Children, depth + 1);
        }
    }

    private static void WriteComponents(SolutionModel model, string dir)
    {
        var md = new StringBuilder();
        md.AppendLine("# Component inventory");
        md.AppendLine();
        md.AppendLine("| Component type | Identifier |");
        md.AppendLine("| --- | --- |");
        foreach (var component in model.RootComponents
                     .OrderBy(c => c.TypeName).ThenBy(c => c.DisplayIdentifier, StringComparer.OrdinalIgnoreCase))
            md.AppendLine($"| {component.TypeName} | {Escape(component.DisplayIdentifier)} |");
        File.WriteAllText(Path.Combine(dir, "components.md"), md.ToString());
    }

    private static void WriteRelationships(SolutionModel model, string dir)
    {
        var md = new StringBuilder();
        md.AppendLine("# Relationships");
        md.AppendLine();
        if (model.OneToManyRelationships.Count > 0)
        {
            md.AppendLine("## One-to-many");
            md.AppendLine();
            md.AppendLine("| Relationship | One | Many | Lookup column | Cascade delete |");
            md.AppendLine("| --- | --- | --- | --- | --- |");
            foreach (var relationship in model.OneToManyRelationships.OrderBy(r => r.SchemaName, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"| `{relationship.SchemaName}` | {model.EntityDisplayName(relationship.ReferencedEntity)} " +
                              $"| {model.EntityDisplayName(relationship.ReferencingEntity)} " +
                              $"| `{relationship.ReferencingAttribute}` | {relationship.CascadeDelete} |");
            md.AppendLine();
        }
        if (model.ManyToManyRelationships.Count > 0)
        {
            md.AppendLine("## Many-to-many");
            md.AppendLine();
            md.AppendLine("| Relationship | Table 1 | Table 2 | Intersect table |");
            md.AppendLine("| --- | --- | --- | --- |");
            foreach (var relationship in model.ManyToManyRelationships.OrderBy(r => r.SchemaName, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"| `{relationship.SchemaName}` | {model.EntityDisplayName(relationship.Entity1)} " +
                              $"| {model.EntityDisplayName(relationship.Entity2)} | `{relationship.IntersectEntity}` |");
            md.AppendLine();
        }
        if (model.InferredLookups.Count > 0)
        {
            md.AppendLine("## Implicit lookup relationships (inferred)");
            md.AppendLine();
            md.AppendLine("Inferred from lookup-shaped columns; not declared in this solution.");
            md.AppendLine();
            foreach (var lookup in model.InferredLookups.OrderBy(l => l.Entity, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"- {model.EntityDisplayName(lookup.Entity)}: `{lookup.AttributeLogicalName}` ({lookup.AttributeType})");
        }
        File.WriteAllText(Path.Combine(dir, "relationships.md"), md.ToString());
    }

    private static void WriteCrossCutting(SolutionModel model, string dir)
    {
        var md = new StringBuilder();
        md.AppendLine("# Automations, roles, apps and settings");
        md.AppendLine();

        if (model.Processes.Count > 0)
        {
            md.AppendLine("## Automations");
            md.AppendLine();
            md.AppendLine("| Name | Kind | Primary table | State |");
            md.AppendLine("| --- | --- | --- | --- |");
            foreach (var process in model.Processes.OrderBy(p => p.KindDisplay).ThenBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"| {Escape(process.Name)} | {process.KindDisplay} " +
                              $"| {(process.PrimaryEntity == "none" ? string.Empty : model.EntityDisplayName(process.PrimaryEntity))} " +
                              $"| {(process.IsActive ? "Active" : "Draft")} |");
            md.AppendLine();
        }

        if (model.CanvasApps.Count > 0)
        {
            md.AppendLine("## Canvas apps");
            md.AppendLine();
            foreach (var app in model.CanvasApps)
            {
                md.AppendLine($"### {Escape(app.DisplayName)}");
                md.AppendLine();
                md.AppendLine($"{app.KindDisplay}, schema name `{app.Name}`" +
                              (string.IsNullOrEmpty(app.AppVersion) ? string.Empty : $", version {app.AppVersion}") + ".");
                md.AppendLine();
                if (!app.HasInternals)
                {
                    md.AppendLine("The `.msapp` is not in this export, so only solution metadata is documented.");
                    md.AppendLine();
                    continue;
                }
                if (app.DataSources.Count > 0)
                    md.AppendLine($"- Tables: {string.Join(", ", app.DataSources.Select(d => $"`{d.LogicalName}`"))}");
                if (app.GlobalVariables.Count > 0)
                    md.AppendLine($"- Global variables (derived from formulas): {string.Join(", ", app.GlobalVariables.Select(v => $"`{v}`"))}");
                if (app.Collections.Count > 0)
                    md.AppendLine($"- Collections (derived from formulas): {string.Join(", ", app.Collections.Select(v => $"`{v}`"))}");
                md.AppendLine();
                foreach (var screen in app.Screens)
                {
                    md.AppendLine($"**{Escape(screen.Name)}** ({screen.CountControls()} controls)");
                    md.AppendLine();
                    foreach (var control in screen.AllControls())
                    {
                        var authored = control.Properties.Count > 0
                            ? " - " + string.Join("; ", control.Properties.Select(p => $"`{p.Key}`"))
                            : string.Empty;
                        md.AppendLine($"- `{control.Name}` ({control.Type}){Escape(authored)}");
                    }
                    md.AppendLine();
                }
            }
        }

        if (model.Agents.Count > 0)
        {
            md.AppendLine("## Agents");
            md.AppendLine();
            foreach (var agent in model.Agents)
            {
                md.AppendLine($"### {Escape(agent.Name)}");
                md.AppendLine();
                md.AppendLine($"Schema name `{agent.SchemaName}`, {agent.AuthenticationModeDisplay}" +
                              (agent.GenerativeActionsEnabled ? ", generative actions enabled" : string.Empty) + ".");
                md.AppendLine();
                if (!string.IsNullOrEmpty(agent.Instructions))
                {
                    md.AppendLine("Instructions:");
                    md.AppendLine();
                    md.AppendLine("```");
                    md.AppendLine(agent.Instructions);
                    md.AppendLine("```");
                    md.AppendLine();
                }
                foreach (var topic in agent.Topics)
                {
                    md.AppendLine($"- **Topic {Escape(topic.DisplayName)}** triggered by: " +
                                  string.Join("; ", topic.TriggerQueries.Select(Escape)));
                    foreach (var message in topic.Messages)
                        md.AppendLine($"  - replies: {Escape(message)}");
                }
                foreach (var tool in agent.Tools)
                    md.AppendLine($"- **Tool {Escape(tool.Name)}** ({tool.Kind}) {Escape(tool.Description)}");
                foreach (var source in agent.KnowledgeSources)
                    md.AppendLine($"- **Knowledge {Escape(source.Name)}** ({source.SourceKind}) {Escape(source.Site)}");
                md.AppendLine();
            }
        }

        var desktopFlows = model.Processes.Where(p => p.DesktopFlow is not null).ToList();
        if (desktopFlows.Count > 0)
        {
            md.AppendLine("## Desktop flows");
            md.AppendLine();
            foreach (var process in desktopFlows)
            {
                var detail = process.DesktopFlow!;
                md.AppendLine($"### {Escape(process.Name)}");
                md.AppendLine();
                md.AppendLine($"{detail.TotalSteps} steps across {detail.Subflows.Count} subflows. " +
                              (detail.Modules.Count > 0 ? $"Modules: {string.Join(", ", detail.Modules)}." : string.Empty));
                md.AppendLine();
                foreach (var subflow in detail.Subflows.Where(s => s.Steps.Count > 0))
                {
                    md.AppendLine($"**{Escape(subflow.Name)}**{(subflow.IsGlobal ? " (global)" : string.Empty)}");
                    md.AppendLine();
                    foreach (var step in subflow.Steps)
                    {
                        md.AppendLine($"{new string(' ', step.Depth * 2)}- `{step.Action}`" +
                                      (step.OutputVariables.Count > 0
                                          ? $" into {string.Join(", ", step.OutputVariables.Select(v => $"`{v}`"))}"
                                          : string.Empty));
                    }
                    md.AppendLine();
                }
            }
        }

        var businessProcessFlows = model.Processes.Where(p => p.BusinessProcessFlow is not null).ToList();
        if (businessProcessFlows.Count > 0)
        {
            md.AppendLine("## Business process flows");
            md.AppendLine();
            foreach (var process in businessProcessFlows)
            {
                var detail = process.BusinessProcessFlow!;
                md.AppendLine($"### {Escape(process.Name)}");
                md.AppendLine();
                md.AppendLine($"Runs on `{process.PrimaryEntity}`. " +
                              $"{detail.Stages.Count} stages, {detail.StepCount} steps.");
                md.AppendLine();
                md.AppendLine("| # | Stage | Steps |");
                md.AppendLine("| --- | --- | --- |");
                foreach (var stage in detail.Stages)
                {
                    var steps = stage.Steps.Count == 0
                        ? "none"
                        : string.Join(", ", stage.Steps.Select(s =>
                            s.DataField.Length > 0
                                ? $"{Escape(s.Name)} (`{s.DataField}`)"
                                : Escape(s.Name)));
                    md.AppendLine($"| {stage.Order} | {Escape(stage.Name)} | {steps} |");
                }
                md.AppendLine();
            }
        }

        if (model.PluginAssemblies.Count > 0 || model.SdkMessageSteps.Count > 0)
        {
            md.AppendLine("## Plugins");
            md.AppendLine();
            foreach (var assembly in model.PluginAssemblies)
            {
                md.AppendLine($"### {Escape(assembly.Name)}");
                md.AppendLine();
                md.AppendLine($"Version {assembly.Version}. Isolation: {assembly.IsolationMode}.");
                md.AppendLine();
                if (assembly.Types.Count > 0)
                {
                    md.AppendLine("Types: " +
                        string.Join(", ", assembly.Types.Select(t => $"`{t.DisplayName}`")));
                    md.AppendLine();
                }
                AppendSteps(md, assembly.Steps);
            }

            // Registrations whose assembly ships in another solution still
            // matter: they run against this solution's tables.
            var orphans = model.SdkMessageSteps
                .Where(s => !model.PluginAssemblies.Any(a => a.Steps.Contains(s))).ToList();
            if (orphans.Count > 0)
            {
                md.AppendLine("### Registrations whose assembly is not in this solution");
                md.AppendLine();
                AppendSteps(md, orphans);
            }
        }

        if (model.OptionSets.Count > 0)
        {
            md.AppendLine("## Choices (option sets)");
            md.AppendLine();
            foreach (var optionSet in model.OptionSets)
                md.AppendLine($"- **{Escape(optionSet.DisplayName)}** (`{optionSet.Name}`, " +
                              $"{(optionSet.IsGlobal ? "global" : "local")}): " +
                              string.Join(", ", optionSet.Options.Select(o => Escape(o.Label))));
            md.AppendLine();
        }

        if (model.SecurityRoles.Count > 0)
        {
            md.AppendLine("## Security roles");
            md.AppendLine();
            foreach (var role in model.SecurityRoles.OrderBy(r => r.Name, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"- **{Escape(role.Name)}**: {role.Privileges.Count} privileges " +
                              $"({string.Join(", ", role.PrivilegeCountsByLevel.OrderBy(kv => kv.Key).Select(kv => $"{kv.Key} {kv.Value}"))})");
            md.AppendLine();
        }

        if (model.AppModules.Count > 0)
        {
            md.AppendLine("## Model-driven apps");
            md.AppendLine();
            foreach (var app in model.AppModules)
                md.AppendLine($"- **{Escape(app.Name)}** (`{app.UniqueName}`), {app.ComponentCount} components");
            md.AppendLine();
        }

        foreach (var siteMap in model.SiteMaps)
        {
            md.AppendLine($"## Navigation: {Escape(siteMap.UniqueName)}");
            md.AppendLine();
            foreach (var area in siteMap.Areas)
                foreach (var group in area.Groups)
                    md.AppendLine($"- {Escape(area.Title)} > {Escape(group.Title)}: " +
                                  string.Join(", ", group.SubAreas.Select(sa =>
                                      string.IsNullOrEmpty(sa.Entity) ? Escape(sa.Title) : $"{Escape(sa.Title)} (`{sa.Entity}`)")));
            md.AppendLine();
        }

        if (model.EnvironmentVariables.Count > 0)
        {
            md.AppendLine("## Environment variables");
            md.AppendLine();
            md.AppendLine("| Name | Type | Required | Default value | Current value |");
            md.AppendLine("| --- | --- | --- | --- | --- |");
            foreach (var variable in model.EnvironmentVariables)
                md.AppendLine($"| `{variable.SchemaName}` | {variable.TypeName} | {(variable.IsRequired ? "Yes" : "No")} " +
                              $"| {(variable.IsSecret ? "[secret]" : Escape(variable.DefaultValue))} " +
                              $"| {(variable.IsSecret ? "[secret]" : variable.HasCurrentValue ? Escape(variable.CurrentValue) : "(not in export)")} |");
            md.AppendLine();
        }

        if (model.WebResources.Count > 0)
        {
            md.AppendLine("## Web resources");
            md.AppendLine();
            foreach (var resource in model.WebResources.OrderBy(r => r.Name, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"- `{resource.Name}` ({resource.TypeName})" +
                              (string.IsNullOrEmpty(resource.DisplayName) ? string.Empty : $": {Escape(resource.DisplayName)}"));
            md.AppendLine();
        }

        if (model.ConnectionReferences.Count > 0)
        {
            md.AppendLine("## Connection references");
            md.AppendLine();
            foreach (var reference in model.ConnectionReferences.OrderBy(r => r.LogicalName, StringComparer.OrdinalIgnoreCase))
                md.AppendLine($"- `{reference.LogicalName}` ({reference.ConnectorShortName})" +
                              (string.IsNullOrEmpty(reference.DisplayName) ? string.Empty : $": {Escape(reference.DisplayName)}"));
        }

        File.WriteAllText(Path.Combine(dir, "solution-artefacts.md"), md.ToString());
    }

    /// <summary>AI text renders as a labelled blockquote, visually apart from extracted fact.</summary>
    private static void AppendAiBlock(StringBuilder md, GeneratedInterpretation interpretation, string text)
    {
        md.AppendLine($"> **{interpretation.Attribution}**");
        md.AppendLine(">");
        foreach (var line in text.Split('\n'))
            md.AppendLine($"> {line.TrimEnd()}");
        md.AppendLine();
    }

    private static string Display(EntityModel entity) =>
        string.IsNullOrEmpty(entity.DisplayName) ? entity.SchemaName : entity.DisplayName;

    private static bool Matches(string name, EntityModel entity) =>
        string.Equals(name, entity.SchemaName, StringComparison.OrdinalIgnoreCase) ||
        string.Equals(name, entity.LogicalName, StringComparison.OrdinalIgnoreCase);

    internal static string FileName(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var cleaned = new string(name.Select(c => invalid.Contains(c) || c == ' ' ? '-' : c).ToArray());
        return cleaned.Trim('-').ToLowerInvariant();
    }

    private static string Escape(string text) => text.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
}
