<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Shieldsmith.Core</AssemblyName>
    <RootNamespace>Shieldsmith.Core</RootNamespace>
  </PropertyGroup>

</Project>
